### ISSUE TITLE
Block timestamps?

### ISSUE THREAD

**Issue by artjomsR** [YU000jp/logseq-plugin-show-page-date#5]
Would it be possible to display block timestamps as well, in addition to page timestamps?

**Comment by YU000jp** [comment]
I once wondered if something similar could be achieved. From what I've researched, Logseq doesn't record timestamps for each block.

Currently, I use "date-nlp" plugin to create date links and assign them to their child blocks, but the number of date links increases on pages. If edit that block later, the date will be inconsistent, so I feel it is necessary to separate it into creation date and modification date (time). In that case, it seems appropriate to create two properties in the parent block.


I tried to explore the possibilities with each intention.
With any of the following intentions:
1. If provide a timestamp for every block
   * The only way by a plugin is to force the property to be retained each time using a plugin. It may be possible to make it a hidden property and display it using a plugin. The plan is to display a timestamp on mouse hover.  But, adding a timestamp to every block can make the graph bloated.
1. A pattern that the user assigns only to the blocks that they want to keep records on
   * User assigns properties to specific blocks each time. It is possible to provide shortcut keys by a plugin to quickly assign properties with timestamps. This is the most feasible.

**Comment by YU000jp** [comment]
Taking this opportunity as an opportunity, I am thinking of creating a "Block Timestamp Shortcut" plugin. Please tell me your opinion. I am planning to create a shortcut key that will give the creation timestamp property or the update timestamp property.

**Comment by YU000jp** [comment]
It was posted on Logseq discuss about wanting to know when a block was written, so I would like to integrate it with that. https://discuss.logseq.com/t/displaying-block-timestamps/24594

**Comment by artjomsR** [comment]
Thank you for replying! Logseq provides `created-at` and `updated-at` properties for blocks, but this functionality is off be default. To enable it, you'd need to change the config

https://discuss.logseq.com/t/how-to-show-created-at-and-updated-at-in-block-properties/21631/4

I've done this and can see the timestamps for blocks. I'm also not aware of any negative consequences of having this flag set to True

https://www.youtube.com/watch?v=fRWwznJFkJM

I've also recently discovered that logseq is planning to migrate to a DB structure, and I'm not sure if they'll keep the same property names. So for now it's probably not worth doing anything fancy beyond simply showing these existing properties

**Comment by YU000jp** [comment]
Is true. That flag is valid.
However, it is not easy to achieve this with a plugin. This is because Logseq does not expose that property. Currently, When displaying, it is necessary to read the database for each block.  It may be faster to change the script of Logseq itself. I'm thinking of a way to do that.  It seems that this cannot be achieved without issuing a pull request to Logseq.

**Comment by YU000jp** [comment]
Mr. @mtravers submitted a pull request. I will finish here.
https://github.com/mtravers/logseq/pull/2

**Comment by artjomsR** [comment]
Thanks for your work :) I'll follow that pr there
